name: google_directions_api
version: 0.6.0
homepage: https://github.com/marchdev-tk/google_directions_api
description: The Directions API is a service that calculates directions between locations. You can search for directions for several modes of transportation.

environment:
  sdk: '>=2.12.0-259.16.beta <3.0.0'

dependencies:

  google_polyline_algorithm: ^2.0.0
  http: ^0.13.0
  flinq: ^1.1.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
